// <auto-generated />
namespace SmartStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Regenerated_Customer_IsCountryManager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Regenerated_Customer_IsCountryManager));
        
        string IMigrationMetadata.Id
        {
            get { return "202010141433567_Regenerated_Customer_IsCountryManager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
